import pickle

with open('score_predict_model.pkl', 'rb') as f:
    loaded_models = pickle.load(f)


#loaded_models[0].predict(X_test)...
#loaded_models[1].predict(X_test)...
#loaded_models[2].predict(X_test)...