FROM agrigorev/model-2025-hairstyle:v1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#COPY hair_classifier_empty.onnx.data .
#COPY hair_classifier_empty.onnx .

COPY lambda_function.py .

CMD ["lambda_function.lambda_handler"]